### ISSUE TITLE
How do I cache files from a sub-domain?

### ISSUE THREAD

**Issue by s7dhansh** [ilan-schemoul/meteor-service-worker#10]
I tried using `cache.addAll([HTMLToCache, 'https://sub.domain.com/'])` but it does not work.

On a side note, in https://github.com/NitroBAY/meteor-service-worker/blob/master/sw.js#L45, why are you using `cache.put(HTMLToCache...)` instead of `cache.put(event.request...`. Isn't the latter better (It ensures even static html to be cached with their respective urls? The former assumes there is only one html at the root.

EDIT: Typo fix

**Comment by stephane-r** [comment]
Hi @s7dhansh 

Maybe you can try with `cache.addAll([HTMLToCache, 'https://sub.domain.com/'])` ?

**Comment by ilan-schemoul** [comment]
Whatever the URL is the HTML returned by the server is the same. The HTML in Meteor 

> is only composed of request (<link> and <script>) to CSS and Javascript files

as @LeG3nDz points out there's a typo it's not `HTMLToCahce` but `HTMLToCache`. If once the typo corrected it's still not working, I'm not sure what the problem.

**Comment by s7dhansh** [comment]
@LeG3nDz @NitroBAY  It was a typo in the issue content. The actual code is proper.
@NitroBAY LEt me explain better. Let's say there is a static html file in public folder of meteor, used for some static content (may be a promotional mail, or an offline.html). Even if it is cached, it will cache it with the key being `HTMLToCache` variable, which is '/'. It can not be the desired behavior, or am I missing somthing?

**Comment by ilan-schemoul** [comment]
@s7dhansh indeed I didn't think about this edge case. Do you have a use case in your current project where how SW handles HTML is actually a problem ?

**Comment by s7dhansh** [comment]
@NitroBAY No, I am not facing any issue for now (except the sub.domain issue), but while going through the code, I wondered why you were using `HTMLToCache` at one place, while `event.request` at another. Ideally, irrespective of `HTMLToCache`, we should always `cache.put` it in `event.request`.

**Comment by ilan-schemoul** [comment]
@s7dhansh No, it's better to store one HTML instead of multiple HTML are they are really the same. I don't think that wasting precious memory for nothing is ideal.
