### ISSUE TITLE
Should this work with a react app?

### ISSUE THREAD

**Issue by vacarsu** [ilan-schemoul/meteor-service-worker#11]
I've implements the service worker and it seems to be caching files, however the page is just blank when I set it to offline in chrome devtools. I get several errors in the service worker 'An unknown error occurred when fetching script'.

<img width="1268" alt="screen shot 2017-02-17 at 8 44 20 pm" src="https://cloud.githubusercontent.com/assets/11384972/23090410/14e3279c-f552-11e6-8665-75fe81f74b60.png">

<img width="1280" alt="screen shot 2017-02-17 at 8 44 46 pm" src="https://cloud.githubusercontent.com/assets/11384972/23090411/17d7393e-f552-11e6-8e74-34d0c6a9c69e.png">

**Comment by ilan-schemoul** [comment]
To answer the title, yes it should. "An unknown error occurred when fetching script" may points out an error in the SW code thus you may want to check again if you copy paste correctly the sw.js. And that you followed the instructions (sw.js in the **root** of the public folder, register it from a `startup` code loaded client-side etc.).
If you followed correctly the instructions and your web is working without the SW I don't know what's the problem.

**Comment by ilan-schemoul** [comment]
Could you create a repository with a reproduction if you still have the bug ? Otherwise feel free to close the issue.
