### ISSUE TITLE
Fonts are not reloaded

### ISSUE THREAD

**Issue by Twisterking** [ilan-schemoul/meteor-service-worker#13]
So I am quite frequently adding more icons to my icomoon iconfont. so the font files change quite frequently as well, but due to the service worker and its caching practices the fonts aren't reloaded at all and always served from cache.

Is there any nice way to maybe do some hash checking from time to time and reload "static" files like icon fonts if they have changed?!

**Comment by ramezrafla** [comment]
I know this is old, but wanted to chime in. In your CSS add a query variable to the fonts `?version=0.2`
This is how you should tell the browser / sw to load a fresh version
