### ISSUE TITLE
Videos are cached by service worker twice sometimes

### ISSUE THREAD

**Issue by tmpg** [ilan-schemoul/meteor-service-worker#16]
I have a video autoplay on load. Most of the times it works but it doesn't when the service worker loads two of the same video, as shown below:

![sw](https://user-images.githubusercontent.com/7082248/30312298-d637f1f0-9766-11e7-9624-721eec764b11.png)

Let me know if you have any suggestions.

Thanks

**Comment by ilan-schemoul** [comment]
I have no clue, sorry. Did you get your issue fixed ?
