### ISSUE TITLE
Exception after reload

### ISSUE THREAD

**Issue by vuhrmeister** [ilan-schemoul/meteor-service-worker#2]
When running my app with your service worker on mobile (as standalone app) I get an error in the developer console. On desktop it works just fine.

Though, the app seems to work. Don't know if that error is critical.

I configured the `HTMLToCache` property to use `/dashboard` as value.

<img width="969" alt="bildschirmfoto 2016-10-17 um 19 58 25" src="https://cloud.githubusercontent.com/assets/2188790/19449119/913d4912-94a4-11e6-9154-9fa0a1ceade2.png">

The second error seems to be a chrome issue: http://stackoverflow.com/questions/33328579/service-worker-throwing-an-neterr-file-exists-error

**Comment by ilan-schemoul** [comment]
The first error sometimes appears but doesn't seems critical as everything's working for now. I'm not sure how can I reproduce it, nor why `Response` is said to be used although it shouldn't as I use clone. So I'm open to ideas but I don't know why this error randomly occurs.
As you said the second error can be ignored.

**Comment by vuhrmeister** [comment]
Alright, thx for clarification.

**Comment by ilan-schemoul** [comment]
I close this issue as it's not really an issue actually. It's a bit weird and annoying but otherwise it doesn't cause any trouble.

**Comment by ilan-schemoul** [comment]
I'm glad #3 fix this issue.

**Comment by vuhrmeister** [comment]
great! Glad to hear. Will update my script.
