### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by wivn** [ilan-schemoul/meteor-service-worker#20]
I love the project, I've been playing around with the code and for the most part, it works great! I would like to use some of the code in a project of my own, so it would be fantastic to see if @NitroBAY could license this under a permissive license. Thank you for your hard work!

**Comment by ilan-schemoul** [comment]
Hello,
Good idea thanks. I don't know much about license so I just ready about it and MIT license seems simple and good ?
Do you think that's the best license that I could choose or should I choose another one ?
As MIT is simple, very permissive, doesn't provide warranty and the only requirement is to credit me (on the sw.js as I've already wrote it is enough for me).

**Comment by wivn** [comment]
The MIT license is a solid license, and a lot of projects use it. The license you choose depends on what you want your code to be used for. If you want to allow anyone to use your code for nearly any purpose and get widespread use, the MIT license is probably the way to go.

**Comment by ilan-schemoul** [comment]
commit dc5465c09f40 added MIT license.
