### ISSUE TITLE
POST exception

### ISSUE THREAD

**Issue by raphaelarias** [ilan-schemoul/meteor-service-worker#21]
Thanks for the initiative.

We keep getting this error:

`Uncaught (in promise) TypeError: Request method 'POST' is unsupported
    at sw.js:58`

![image](https://user-images.githubusercontent.com/5008166/50416175-4e558700-0873-11e9-9612-c162ea75a191.png)

The line with error is:
`caches.open(version).then(cache => cache.put(event.request, clonedResponse));`

Would you know why is it throwing an error on a dynamic import?

For now I've put:

`if (event.request.method !== 'POST') {
            caches.open(version).then(cache => cache.put(event.request, clonedResponse));
          }`

**Comment by ilan-schemoul** [comment]
Because Service Workers cannot cache POST, your solution is valid. I'll update the SW later. When I created this SW dynamic-import was not a thing therefore I didn't see that use case. Thanks.

**Comment by guidouil** [comment]
Now I'm getting it to. Can you please fix it ? Pretty please 🙏

**Comment by raphaelarias** [comment]
PS: We had to stop using the SW for now, because even with my workaround, it was breaking some of our uploads to S3. We didn't have time to reproduce, and I don't know exactly when it happened, but by removing the SW it fixed.
