### ISSUE TITLE
Maintenance for this project

### ISSUE THREAD

**Issue by jankapunkt** [ilan-schemoul/meteor-service-worker#25]
Hey @NitroBAY, 

I would like to maintain the repo. I've seen that you are not really avtive and I think there are still lots of users out there relying on this. There are some open PRs and issues and I will soon have the next PR for 206 streaming support.

I know, I can also make a fork but I'd rather like to keep the credits to you as original owner of it and just maintain issues/PRs what do you think?

**Comment by jankapunkt** [comment]
cc @mullojo @EloyID

**Comment by ilan-schemoul** [comment]
Hello,
I'm really sorry I did not see this earlier.
Yes I would be very glad to have you as a maintainer if you are willing to do this. My personnal project that inspired me this repository transitioned away from Meteor.
Are you still willing to do this ?

**Comment by ilan-schemoul** [comment]
@mullojo @EloyID @jankapunkt I am still looking for a maintainer. Preferably someone who makes PRs first.

**Comment by jankapunkt** [comment]
@ilan-schemoul could you also imagine this repo being transfered to [Meteor-Community-Packages](https://github.com/Meteor-Community-Packages/) org? It's a community-driven org with many people taking care of many Meteor Packages. 

All credits remain in order to honor the original authors plus whatever the license defines. What do you think?

**Comment by ilan-schemoul** [comment]
@jankapunkt  Sure I can do that. 
I am a bit disappointed it won't appear in my repositories because having open source projects can help with job hunting but I'll do it. 
Can you kindly tell me how to proceed ?
BTW I don't care too much with licenses. If the community thinks there's something better I'm fine with it. But yeah crediting my full name (Ilan Schemoul) would be appreciated thanks.

**Comment by jankapunkt** [comment]
cc @storytellercz do you know any alternatives and how the project is actually transferred?

**Comment by StorytellerCZ** [comment]
Yes, in the settings if you scroll down on the initial page there is `Transfer ownership`, you then specify `Meteor-Community-Packages` as the receiver and I'll take care of the rest.
